#!/bin/bash

PREVIEWER="${PREVIEWER-okular}"
PREVIEWEROPTS="${PREVIEWEROPTS---unique}"
workdir="/tmp/$( basename "$0" ).$$"
delay=5
mode=gphoto

while [ "$1" != "" ]; do
  case "$1" in
    -t|--test)
      mode="test"
      ;;
    *)
      echo "Usage: $0 [-t|--test]"
      exit
      ;;
  esac
  shift
done

grab_preview_test() {
  wget http://lorempixel.com/g/400/200 -O lorempixel_${RANDOM}
}

grab_preview_gphoto() {
  gphoto2 --capture-preview --quiet
}

shoot() {
  # DISPLAY= gphoto2 --quiet --capture-preview >/dev/null
  grab_preview_$mode
  if [ "$?" != "0" ]; then
    echo "Error grabbing preview image"
    return 1
  fi
  new_file="$( ls -t * | head -n 1 )"
  echo "$new_file"
  return 0
}

preview() {
  echo "Opening file $@" >&2
  $PREVIEWER $PREVIEWEROPTS $@ 
}

mkdir -p "$workdir"
cd "$workdir"

action=""

while [ "$action" != "q" ]; do
  if [ "$timed_out" == "true" ]; then
    read -n 1 -t $delay action
    timed_out="false"
  else
    read -n 1 -p "Enter action ('?' shows available actions): " -t $delay action
  fi
  [ "$action" != "" ] && echo
  case "$action" in
    "?")
      echo "Available actions: "
      echo -e "\t?: shows this help message"
      echo -e "\tq: exits this program"
      echo -e "\t+: increase shooting interval"
      echo -e "\t-: decrease shooting interval"
      ;;
    "+")
      (( delay++ )); echo "Interval increased to $delay"
      ;;
    "-")
      if [ $delay -gt 1 ]; then
       (( delay-- )); echo "Interval decreased to $delay"
      else
       echo "Interval already at $delay; skipping"
      fi
      ;;
    "")
      timed_out="true"
      file="$( shoot)"
      [ "$?" == "0" ] && preview "$file" &
      ;;
    q)
      ;;
    *)
      echo "Unknown action."
      ;;
  esac
done

echo ""
cd -
rm -rf "$workdir"

